import { ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";
import { home } from "../content/home";
import { pillars } from "../content/pillars";
import { fiveFs } from "../content/fiveFs";
import { images } from "../content/images";
import { Button } from "../components/ui/Button";
import { DraftBadge } from "../components/ui/DraftBadge";
import { Reveal } from "../components/ui/Reveal";
import { SectionHeader } from "../components/ui/SectionHeader";
import { PageHeader } from "../components/sections/PageHeader";
import { ProcessFlow } from "../components/graphics/ProcessFlow";
import { CtaBand } from "../components/sections/CtaBand";

const accent = ["border-accent-teal", "border-accent-amber", "border-accent-coral", "border-accent-slate"];

export function Home() {
  return <div>
    <PageHeader eyebrow={home.hero.eyebrow} title={home.hero.title} body={home.hero.body} image={images["home-hero"]}><div className="mt-8 flex flex-wrap items-center gap-5"><Button>Get started</Button><a href="#pillars" className="inline-flex items-center gap-2 text-sm font-semibold hover:underline">See what we do <ArrowRight size={16} /></a></div><p className="mt-6 max-w-[52ch] text-sm leading-6 text-text-muted">{home.hero.trust}</p></PageHeader>
    <section className="mx-auto max-w-container px-5 py-20 md:px-10 md:py-28"><SectionHeader eyebrow="WHAT CHANGES" title="What actually changes." /><div className="grid gap-4 md:grid-cols-2">{home.outcomes.map((card, index) => { const Icon = card.icon; return <Reveal key={card.title} delay={index * .04}><article className={`${index === 0 ? "md:row-span-2" : ""} h-full bg-paper-elevated p-7 md:p-8`}><Icon size={25} strokeWidth={1.5} /><h3 className="mt-6 font-display text-3xl leading-tight">{card.title}</h3><p className="mt-3 max-w-[45ch] text-sm leading-6 text-text-muted">{card.body}</p>{card.details && <ul className="mt-6 grid gap-3 text-sm leading-5">{card.details.map((detail) => <li key={detail} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-teal" />{detail}</li>)}</ul>}</article></Reveal>; })}</div></section>
    <section id="pillars" className="scroll-mt-24 bg-white"><div className="mx-auto max-w-container px-5 py-20 md:px-10 md:py-28"><SectionHeader eyebrow="OUR PILLARS" title={<>Four areas. <em className="font-light">One discipline.</em></>}><p className="mt-6 max-w-[68ch] text-lg leading-7 text-text-muted">{home.pillarsIntro}</p></SectionHeader><img src={images["home-pillars"].src} alt={images["home-pillars"].alt} className="mx-auto my-12 w-full max-w-[720px] border border-rule bg-white shadow-sm" loading="lazy" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{pillars.map((pillar, index) => <Link key={pillar.slug} to={pillar.to} className={`border-l-4 ${accent[index]} bg-paper p-6 transition-colors hover:bg-paper-elevated`}><h3 className="font-display text-[26px] leading-tight">{pillar.teaser.title}</h3><p className="mt-2 font-display text-lg font-light italic text-text-muted">{pillar.teaser.tagline}</p><p className="mt-4 text-sm leading-6 text-text-muted">{pillar.teaser.body}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">Explore {pillar.name} <ArrowRight size={15} /></span></Link>)}</div></div></section>
    <section id="five-fs" className="scroll-mt-24 mx-auto max-w-container px-5 py-20 md:px-10 md:py-12"><SectionHeader eyebrow="THE FIVE FS" title="What every model we build has in common." /><div className="border-t border-rule">{fiveFs.map((item) => <Link key={item.slug} to={item.to} className="grid gap-2 border-b border-rule py-4 transition-colors hover:bg-paper-elevated md:grid-cols-[55px_1fr_1.4fr_1.1fr] md:items-center md:gap-5 md:py-2"><span className="font-mono text-xs text-text-muted">{item.eyebrow.split("—")[1]?.trim()}</span><span className="font-display text-2xl">{item.name}</span><span className="text-sm leading-5 text-text-muted">{item.table.def}</span><span><strong className="block text-sm">{item.table.heading}</strong><span className="text-sm leading-5 text-text-muted">{item.table.desc}</span></span></Link>)}</div></section>
    <section id="process" className="scroll-mt-24 bg-paper-elevated"><div className="mx-auto max-w-container px-5 py-20 md:px-10 md:py-28"><SectionHeader eyebrow="HOW THE WORK RUNS" title="Every number takes the same five steps." /><Link to="/pillars/modern-governance" aria-label="See how a Modelly model is built" className="block border border-rule bg-white p-4 transition-shadow hover:shadow-md md:p-8"><ProcessFlow /></Link><Link to="/pillars/modern-governance" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold">See how a Modelly model is built <ArrowRight size={15} /></Link></div></section>
    <section id="toolkit" className="scroll-mt-24 mx-auto max-w-container px-5 py-20 md:px-10 md:py-28"><SectionHeader eyebrow="THE TOOLKIT" title="Six tools that travel with every engagement."><p className="mt-6 max-w-[62ch] text-lg leading-7 text-text-muted">{home.toolkitIntro}</p></SectionHeader><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{home.tools.map((tool) => { const Icon = tool.icon; return <Link key={tool.slug} to={`/models/${tool.slug}`} className="bg-paper-elevated p-7 transition-colors hover:bg-white"><Icon size={25} strokeWidth={1.5} /><h3 className="mt-6 font-display text-2xl">{tool.name}{tool.draft && <DraftBadge />}</h3><p className="mt-3 text-sm leading-6 text-text-muted">{tool.body}</p><ArrowRight size={16} className="mt-6" /></Link>; })}</div></section>
    <CtaBand />
  </div>;
}
