const base = [{ label: "Home", to: "/" }, { label: "Fundamentals", to: "/five-fs" }];

export const fiveFs = [
  { slug: "f1", name: "Functions", number: "F1", variant: "bars", eyebrow: "MODELLING FUNDAMENTALS", breadcrumb: base, image: "f1", bullets: ["Current spreadsheet formulas, including LET, FILTER, UNIQUE, INDEX and MATCH", "Formulas defined centrally through named ranges, not repeated cell by cell", "One change propagates through every scenario and every period", "Calculation logic anyone can trace, because it lives in one place", "No hunting through worksheets for the copy that did not get updated"], table: { def: "Current spreadsheet formulas — LET, FILTER, UNIQUE, INDEX and MATCH — defined once through named ranges.", heading: "One definition, one change", desc: "Update a formula once and the whole model follows." } },
  { slug: "f2", name: "Features", number: "F2", variant: "flow", eyebrow: "MODELLING FUNDAMENTALS", breadcrumb: base, image: "f2", bullets: ["Tables and structured references, so ranges grow without breaking formulas", "Power Query brings data in the same way every period — imports become refreshes", "Power Pivot handles data volumes a single worksheet cannot", "Named functions package repeated logic without a line of code", "No macros. No VBA."], table: { def: "Native capabilities used the way they were designed: Tables, Power Query, Power Pivot, named functions.", heading: "Nothing for IT to block", desc: "Built from native features only. Files open clean on locked-down machines." } },
  { slug: "f3", name: "Format", number: "F3", variant: "table", eyebrow: "MODELLING FUNDAMENTALS", breadcrumb: base, image: "f3", bullets: ["Cell styles classify every cell by purpose — inputs, formulas and outputs are visibly different", "Number formats locked by measure type, with line-by-line overrides when needed", "A toggle between modelling mode and presentation mode", "Charts and reporting packs that stay consistent without manual reformatting", "Change a style once and every cell carrying it follows"], table: { def: "Colour, type, borders and layout controlled centrally through cell styles and conditional formatting.", heading: "Formats locked by measure", desc: "A rate cannot show as $12.34 in one row and $12.345 in the next." } },
  { slug: "f4", name: "Framework", number: "F4", variant: "waterfall", eyebrow: "MODELLING FUNDAMENTALS", breadcrumb: base, image: "f4", bullets: ["A relational structure of tables and helper rows", "One workbook, one worksheet — no satellite files to reconcile", "Scenarios switched from a drop-down, not a new file", "Periods and line items added without touching the structure", "Cross-references that survive change"], table: { def: "A relational structure of tables and helper rows that lets models grow without a rebuild.", heading: "Extend without rebuilding", desc: "Add a scenario, a period or a line item without restructuring anything." } },
  { slug: "f5", name: "Foundation", number: "F5", variant: "grid", eyebrow: "MODELLING FUNDAMENTALS", breadcrumb: base, image: "f5", bullets: ["Naming conventions applied throughout, so nothing needs decoding", "Version control that shows what changed, and when", "Documentation written as the model is built, not after", "A model summary sheet that explains the file to a stranger", "Standards that help the model outlast its author"], table: { def: "The standards underneath it all: naming, version control, documentation, a readable summary sheet.", heading: "Readable without a handover", desc: "A summary sheet anyone can read without a call to the author." } },
];
