export const meta = {
  "/": { title: "Modelly — Less time producing information. More time using it.", description: "Modelly builds planning, forecasting and reporting systems that give finance teams more time to use information." },
  "/pillars/enterprise-systems": { title: "Where your numbers come from. — Modelly", description: "Review the systems your reporting depends on and fix the handoffs where reporting breaks." },
  "/pillars/accounting-processes": { title: "How data becomes numbers you trust. — Modelly", description: "Map the close, reconciliations and reporting, then remove the manual parts that slow the work." },
  "/pillars/modern-governance": { title: "Models that keep working after we leave. — Modelly", description: "Build models your team can extend, with controls, checks and documentation designed into the work." },
  "/pillars/ai": { title: "AI, used narrowly and well. — Modelly", description: "A narrow, practical approach to AI that keeps documentation and model assumptions current." },
  "/five-fs/f1": { title: "Functions — Modelly", description: "Current formulas defined once through named ranges, so one change follows through the model." },
  "/five-fs/f2": { title: "Features — Modelly", description: "Native capabilities used the way they were designed, with files that open clean on locked-down machines." },
  "/five-fs/f3": { title: "Format — Modelly", description: "Formatting controlled centrally through cell styles and conditional formatting." },
  "/five-fs/f4": { title: "Framework — Modelly", description: "A relational structure that lets models grow without a rebuild." },
  "/five-fs/f5": { title: "Foundation — Modelly", description: "Naming, version control, documentation and a summary sheet that anyone can read." },
  "/models/charter": { title: "Charter — Modelly", description: "Purpose, scope, stakeholders and ground rules agreed before anything gets built." },
  "/models/raid-dar": { title: "RAID.DAR — Modelly", description: "Risks, assumptions, issues and dependencies, each carrying a decision, action and owner." },
  "/models/rascix": { title: "RASCIX+ — Modelly", description: "A responsibility matrix that keeps who does what current." },
  "/models/requirements-matrix": { title: "Requirements Matrix — Modelly", description: "Every requirement traced from request to delivery." },
  "/models/work-plan": { title: "Work Plan — Modelly", description: "Tasks and milestones that move when reality does." },
  "/models/workback-schedule": { title: "Workback Schedule — Modelly", description: "Start at the deadline and work backwards." },
  "/about": { title: "About Us — Modelly", description: "The people who sell you the work are the people who do it." },
  "/get-started": { title: "Start with a diagnostic. — Modelly", description: "A few questions, about two minutes. One of us reads every answer." },
  "/privacy": { title: "Privacy policy — Modelly", description: "Modelly privacy policy." },
  "/terms": { title: "Terms of use — Modelly", description: "Modelly terms of use." },
  "/404": { title: "That page does not exist. — Modelly", description: "The link may be out of date. Everything is one click away." },
};
