const base = [{ label: "Home", to: "/" }, { label: "Project Management Framework", to: "/project-management-framework" }];

export const models = [
  { slug: "charter", name: "Charter", variant: "grid", eyebrow: "PROJECT MANAGEMENT FRAMEWORK", breadcrumb: base, image: "charter", bullets: ["Purpose and objectives, in plain language", "Scope — what is in, and just as clearly, what is out", "Stakeholders, roles and ground rules", "Meeting cadence and ways of working", "What done looks like, agreed up front"] },
  { slug: "raid-dar", name: "RAID.DAR", variant: "line", eyebrow: "PROJECT MANAGEMENT FRAMEWORK", breadcrumb: base, image: "raid-dar", bullets: ["Risks, with likelihood, impact and an owner", "Assumptions, logged so they get validated instead of forgotten", "Issues, each with a decision, an action and a repair", "Dependencies, each with a decision, an action and a repair", "A single view of what could stop the work, reviewed on a schedule"] },
  { slug: "rascix", name: "RASCIX+", variant: "flow", eyebrow: "PROJECT MANAGEMENT FRAMEWORK", breadcrumb: base, image: "rascix", bullets: ["Role assignments for every step of a process", "Responsible, approving, supporting, consulted and informed roles", "Approval chains that name a single approver, not a committee", "Gaps and double-assignments made visible at a glance", "Easy to update when the team or the process changes"] },
  { slug: "requirements-matrix", name: "Requirements Matrix", variant: "table", eyebrow: "PROJECT MANAGEMENT FRAMEWORK", breadcrumb: base, image: "requirements-matrix", draft: true, bullets: ["Each requirement with its source and owner", "A priority recorded for each requirement", "Status tracked from captured to delivered", "Traceability from requirement to build to test to sign-off", "A record of what was agreed, when scope questions come up later"] },
  { slug: "work-plan", name: "Work Plan", variant: "waterfall", eyebrow: "PROJECT MANAGEMENT FRAMEWORK", breadcrumb: base, image: "work-plan", bullets: ["Task list with owners and dates", "Dependencies recorded alongside each task", "Milestones that mark real completion, not activity", "Progress and timeline visuals calculated automatically", "Add or remove work without rebuilding the schedule"] },
  { slug: "workback-schedule", name: "Workback Schedule", variant: "bars", eyebrow: "PROJECT MANAGEMENT FRAMEWORK", breadcrumb: base, image: "workback-schedule", draft: true, bullets: ["A fixed end date for the work", "Every dependency mapped backwards from the deadline", "Latest-safe start dates for every task", "Early warning when the slack runs out, while there is still time to act", "Built in the same file discipline as the work plan"] },
];
