const base = [{ label: "Home", to: "/" }, { label: "The Toolkit", to: "/#toolkit" }];
const variants = ["bars", "line", "grid", "waterfall", "table", "flow"];
const make = (slug, name, lede, body, list, engagement, draft = false) => ({ slug, to: `/models/${slug}`, name, variant: variants[slug.length % variants.length], eyebrow: `THE TOOLKIT — ${name.toUpperCase()}`, breadcrumb: [...base], h1: name, lede, body, draft, sections: [{ h2: "What's inside", list }, { h2: "On your engagement", body: engagement }] });

export const models = [
  make("charter", "Charter", "Agreed before anything gets built.", "The kickoff document: purpose, scope, goals, stakeholders and ground rules, agreed in writing before work starts. It is also what we point at when scope starts moving.", ["Purpose and objectives, in plain language", "Scope — what is in, and just as clearly, what is out", "Stakeholders, roles and ground rules", "Meeting cadence and ways of working", "What done looks like, agreed up front"], "Every Modelly engagement opens with a charter. It takes one session to agree and saves weeks of drift. Yours to keep and reuse on any project, not only ours."),
  make("raid-dar", "RAID.DAR", "Issue tracking with teeth.", "Risks, assumptions, issues and dependencies — each carrying a decision, an action and a repair path, with an owner's name against it. Nothing sits in the log without someone responsible for it.", ["Risks, with likelihood, impact and an owner", "Assumptions, logged so they get validated instead of forgotten", "Issues and dependencies, each with a decision, an action and a repair", "A single view of what could stop the work, reviewed on a schedule"], "The log is reviewed at every checkpoint and handed over live at the end, so the discipline continues after we leave."),
  make("rascix", "RASCIX+", "Who does what, kept current.", "A responsibility matrix: who is responsible, who approves, who supports, who is consulted, who is informed — assigned per step of the process, not per person, so gaps and overlaps become visible.", ["Role assignments for every step of a process", "Approval chains that name a single approver, not a committee", "Gaps and double-assignments made visible at a glance", "Easy to update when the team or the process changes"], "RASCIX+ is also how we run the model inventory during a diagnostic: every model your team depends on, its owner, and its risks and gaps in one view."),
  make("requirements-matrix", "Requirements Matrix", "Every requirement, traced from request to delivery.", "A single register of what the build must do: each requirement captured, prioritised, owned and traced through design, build and testing to sign-off. It is how “I thought it would do X” gets settled before the build, not after.", ["Each requirement with its source, priority and owner", "Status tracked from captured to delivered", "Traceability from requirement to build to test to sign-off", "A record of what was agreed, when scope questions come up later"], "The matrix is agreed alongside the charter and closed out at handover, so nothing promised goes missing and nothing unpromised sneaks in.", true),
  make("work-plan", "Work Plan", "Tasks and milestones that move when reality does.", "The forward schedule: tasks, owners, milestones and dates, with progress tracked automatically. Add or remove items without breaking the plan. Dates move when reality does, rather than quietly going stale.", ["Task list with owners, dates and dependencies", "Milestones that mark real completion, not activity", "Progress and timeline visuals calculated automatically", "Add or remove work without rebuilding the schedule"], "The plan is shared, not private: your team sees the same dates we do, updated as the work moves."),
  make("workback-schedule", "Workback Schedule", "Start at the deadline. Work backwards.", "For work with a fixed end date — a budget presented to the board, a filing, a go-live — the schedule starts at the deadline and works backwards, so every task carries the latest date it can start without putting the deadline at risk.", ["A fixed end date, and every dependency mapped backwards from it", "Latest-safe start dates for every task", "Early warning when the slack runs out, while there is still time to act", "Built in the same file discipline as the work plan"], "Budget cycles and month-end are deadline work. This is the schedule that keeps them from ending in a weekend.", true),
];
